#ifndef CONF_H
#define CONF_H

#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080

#define PLAYER_ROTATION_SPEED 100
#define PLAYER_MOVEMENT_SPEED 100
#define PLAYER_ACCEL_SPEED 4
#define PLAYER_DECEL_SPEED .5

#define PROJECTILE_RADIUS 3
#define PROJECTILE_SPEED 350
#define PROJECTILE_LIFETIME_SECONDS 2
#define PROJECTILE_FADEOUT_START_REMAINING .15

#define ASTEROID_RADIUS_LARGE 30
#define ASTEROID_RADIUS_MEDIUM 20
#define ASTEROID_RADIUS_SMALL 15

#define ASTEROID_LARGE_SPEED_MIN 20
#define ASTEROID_LARGE_SPEED_MAX 50
#define ASTEROID_MEDIUM_SPEED_MIN 30
#define ASTEROID_MEDIUM_SPEED_MAX 70
#define ASTEROID_SMALL_SPEED_MIN 40
#define ASTEROID_SMALL_SPEED_MAX 110

#define ASTEROID_SPAWN_Y_TOP -14
#define ASTEROID_SPAWN_Y_BOTTOM SCREEN_HEIGHT + 14
#define ASTEROID_SPAWN_X_LEFT -14
#define ASTEROID_SPAWN_X_RIGHT SCREEN_WIDTH +14

#define ASTEROID_ANGLE_ERROR_MIN 150
#define ASTEROID_ANGLE_ERROR_MAX 220

#define DRAW_DIR true
#define DRAW_DIR_LEN 200

#endif
